apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3

  plugins:
  - name: plugin-generic-exporter.leonardoce.io
    parameters:
      configMapName: sql-exporter-config

  storage:
    size: 1Gi
