# From https://raw.githubusercontent.com/justwatchcom/sql_exporter/master/examples/kubernetes/configmap.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-exporter-config
data:
  config.yml: |
    ---
    jobs:
    - name: "master-nodes"
      interval: '1m'
      connections:
      - 'postgres:///postgres?host=/controller/run&user=postgres'
      queries:
      - name: "pg_settings"
        help: "Values of PostgreSQL runtime settings"
        labels:
          - "name"
        values:
          - "setting"
        query:  |
                SELECT
                  name::text,
                  setting::float
                FROM pg_settings
                WHERE
                  vartype IN ('integer','real')
                UNION
                SELECT
                  name::text,
                  CASE setting WHEN 't' THEN 1::float ELSE 0::float END
                FROM pg_settings
                WHERE
                  vartype = 'bool';
      - name: "pg_stat_database"
        help: "PostgreSQL Database stats"
        labels:
          - "datname"
        values:
          - "numbackends"
          - "xact_commit"
          - "xact_rollback"
          - "blks_read"
          - "blks_hit"
          - "tup_returned"
          - "tup_fetched"
          - "tup_inserted"
          - "tup_updated"
          - "tup_deleted"
          - "conflicts"
          - "temp_files"
          - "deadlocks"
          - "blk_read_time"
          - "blk_write_time"
        query:  |
                SELECT
                  datname::varchar,
                  numbackends::float,
                  xact_commit::float,
                  xact_rollback::float,
                  blks_read::float,
                  blks_hit::float,
                  tup_returned::float,
                  tup_fetched::float,
                  tup_inserted::float,
                  tup_updated::float,
                  tup_deleted::float,
                  conflicts::float,
                  temp_files::float,
                  deadlocks::float,
                  blk_read_time::float,
                  blk_write_time::float
                FROM pg_stat_database
                WHERE datid != 0;
      - name: "connections"
        help: "Number of connections in different states"
        labels:
          - "datname"
          - "usename"
          - "state"
        values:
          - "count"
        query:  |
                SELECT
                  datname::text,
                  usename::text,
                  state::text,
                  COUNT(state)::float AS count
                FROM pg_stat_activity
                GROUP BY datname, usename, state
                HAVING datname IS NOT NULL AND usename IS NOT NULL;
      - name: "db_sizes"
        help: "Database Sizes"
        labels:
          - "dbname"
        values:
          - "dbsize"
        query:  |
                SELECT
                  datname::text AS dbname,
                  pg_database_size(datname)::float AS dbsize
                FROM pg_database;
      - name: "replication_senders_count"
        help: "Replication Senders connected"
        values:
          - "count"
        query:  |
                SELECT
                  COUNT(*)::float AS count
                FROM
                  pg_stat_replication;
      - name: "pg_is_in_recovery"
        help: "Bool flag if the node is in recovery"
        values:
          - "case"
        query:  |
                SELECT
                  CASE pg_is_in_recovery() WHEN 't' THEN 1::float ELSE 0::float END;
